In [3]:
#Program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.


nums = (i for i in range(2000, 3200 + 1, 5) if i % 7 == 0) 
print("\n", *nums) 


 2030 2065 2100 2135 2170 2205 2240 2275 2310 2345 2380 2415 2450 2485 2520 2555 2590 2625 2660 2695 2730 2765 2800 2835 2870 2905 2940 2975 3010 3045 3080 3115 3150 3185


In [6]:
# Python program to find the factorial of a number provided by the user.

# change the value for a different result
num = 8

# To take input from the user
#num = int(input("Enter a number: "))

factorial = 1

# check if the number is negative, positive or zero
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

The factorial of 8 is 40320


In [9]:
#With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). Then, the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  

number = int(input("Type a number: "))

numberDict = {}
for i in range(1, number+1):
    numberDict[i] = i*i

print(numberDict)

Type a number: 7
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}


In [11]:
#Given a non-empty string and an integral n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

def remove_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
print(remove_char('Kitten', 0))
print(remove_char('Kitten', 3))
print(remove_char('Kitten', 5))

itten
Kiten
Kitte


In [24]:
#Write a NumPy program to convert a NumPy array into a Python list structure.

import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x.tolist())
print("Array to list:")
print(x.tolist())

Original array elements:
[[0, 1], [2, 3], [4, 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [28]:
#Write a NumPy program to compute the covariance matrix of two given arrays. 

import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("Covariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]
Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [32]:
#Write a program that calculates and prints the value according to the given formula: Q= Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)

Provide D: 100,120,150
[18, 20, 22]
